### ISSUE TITLE
Use React Router to fix this contacts app

### ISSUE THREAD

**Issue by brookCITS** [brookCITS/route-params#1]
### Tasks

- [ ] Set up a BrowserRouter in the index.tsx file with the structure you see in the picture (Don’t forget to import the components into index.tsx before including them in the router configuration).

- [ ] Utilize the ‘useParam( )’ hook to grab the url parameters associated with this route (aka id)

- [ ] Grab the contact details from the array using the id you just extracted from the url

### Evaluation
Evaluate this task using [this rubric](https://docs.google.com/document/d/1Y-gYLjtAkaXjGSL4GwrUzfLVBqRq4HnKrgQkfByi6d8/edit?usp=sharing).
- Provide a score and a reasoning for each dimension
- Provide a general feedback for improving this task
